config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/show'

  get 'comments/destroy'

  get 'articles/index'

  root 'public_controller#home'
  get '/contact', to: 'public_controller#contact'
  get    '/all',  to: 'users#all'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/edit',  to: 'users#edit'
  get '/delete',  to: 'users#destroy'
  resources :users
  resources :blogs do
    resources :articles
  end
  resources :articles do
    resources :comments
  end
  resources :tags, only: [:index, :show]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :articles, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
    def show
      @blog = Blog.find(params[:id])
      @article = Article.all
    end

    def new
      @blog = Blog.new
    end

    def create
      @user = current_user
      @blog = @user.blogs.create(blog_params)
      if @blog.save(blog_params)
        redirect_to blog_path(@blog)
      else
        render 'new'
      end
    end

    def edit
      @blog = Blog.find(params[:id])
    end

    def update
      @blog = Blog.find(params[:id])
      if @blog.update(blog_params)
        redirect_to blog_path(@blog)
      else
        render 'edit'
      end
    end

    def index
      @blog = Blog.all

      respond_to do |format|
        format.html
        format.pdf do
          pdf = Blog_Pdf.new
          send_data pdf.render, filename: 'blog.pdf', type: 'application/pdf', disposition: "inline"
        end
      end
    end

    def destroy
      @blog = Blog.find(params[:id])
      @blog.destroy
      redirect_to blogs_path
    end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

    private
    def blog_params
      params.require(:blog).permit(:title)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="formularz">
  <h1>Edit blog</h1>
  <%= form_for @blog, url: blog_path(@blog) do |form| %>
    <% if @blog.errors.any? %>
      <div class="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this user from being saved:</h2>

        <% @blog.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="pokaz_blogi">
  <h1>Listing blogs</h1>
  <% if current_user %>
    <%= link_to 'New blog', new_blog_path %>
    <p class="pdf">
      <%= link_to 'PDF', blogs_path(format: 'pdf') %>
    </p>
  <% end %>
  <table>

    <% @blog.each do |blog| %>
      <tr>
        <td><%= link_to blog.title, blog_path(blog) %></td>
        <% if current_user %>
          <% if current_user.id == blog.user_id %>
            <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td><%= link_to 'Destroy', blog_path(blog),
                             method: :delete,
                             data: {confirm: 'Are you sure?'} %></td>
            <% end %>
        <% end %>
      </tr>
      </tr>
    <% end %>
  </table>
  <br>
  <li class="przycisk"><%= link_to 'Back', root_path %></li>

</div>

app/views/blogs/new.html.erb
<div class="formularz">
  <% if current_user %>
    <% if @blog.errors.any? %>
      <div class="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this user from being saved:</h2>

        <% @blog.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <h1>New Blog</h1>

    <%= form_with model: @blog, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <% else %>
    <div>
      <h3>
        You must log in
      </h3>
    </div>
  <% end %>
  <%= link_to 'Back', :back %>
</div>

app/views/blogs/show.html.erb
<% provide(:title, @blog.title) %>
<div>
  <div class="pokaz_artykoly">
    <div class="row">
      <aside class="col-md-4">
        <section class="blog_info">
          <h1>
            <%= @blog.title %><br>
          </h1>
        </section>
      </aside>
    </div>

    <h1>Listing Articles</h1>
    <% if current_user %>
      <% if current_user.id == @blog.user_id %>
        <%= link_to 'New article', new_blog_article_path(@blog.id) %>
        <p class="pdf">
          <%= link_to 'PDF', blogs_path(format: 'pdf') %><br>
        </p><br><br>
      <% end %>
    <% end %>
      <% @article.each do |article| %>
          <% if article.blog_id == @blog.id %>
            <div class="article">
              <table>
                  <tr><%= link_to article.title, blog_article_path(@blog,article) %></tr><br><br>
                  <tr><%=image_tag article.image(:original) %></tr><br>
                  <% if current_user %>
                    <% if current_user.id == @blog.user_id %>
                      <tr>
                        <td><%= link_to 'Edit', edit_blog_article_path(@blog,article) %></td><td></td>
                        <td><%= link_to 'Destroy', blog_article_path(@blog,article),
                                      method: :delete,
                                      data: {confirm: 'Are you sure?'} %></td>
                      </tr>
                    <% end %>
                  <% end %>
              </table>
            </div>
          <% end %>
      <% end %>

    </table>
<br>
<br>
<br>

    <%= link_to 'Back', blogs_path %>
  </div>
</div>