config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/show'

  get 'comments/destroy'

  get 'articles/index'

  root 'public_controller#home'
  get '/contact', to: 'public_controller#contact'
  get    '/all',  to: 'users#all'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/edit',  to: 'users#edit'
  get '/delete',  to: 'users#destroy'
  resources :users
  resources :blogs do
    resources :articles
  end
  resources :articles do
    resources :comments
  end
  resources :tags, only: [:index, :show]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy
  acts_as_taggable_on :tags
  has_attached_file :image, :styles => { :original => '450x450', :thumb => '50x50', :good => '453x453' },:default_url => "pobrane.jpg"
  validates_attachment :image, presence => true,
                       :content_type => {:content_type => ["image/jpeg", "image/jpg", "image/png"]}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, except: [:show]

  def index
    @article = Article.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = Article_Pdf.new(@article)
        send_data pdf.render, filename: 'article.pdf', type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @article = @blog.articles.create(article_params)
    if @blog.save
      redirect_to blog_path(@article.blog_id)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to blog_path(@article.blog_id)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to blog_path(@article.blog_id)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :image, :tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with scope: @article, url: blog_articles_path, html: {multipart: true}, local: true do |form| %>

  <% if @article.errors.any? %>
    <div class="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@article.errors.count, "error") %>.
      </div>
      <% @article.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.label :tags %><br>
    <%= form.text_field :tag_list, value: form.object.tag_list.to_s %>
  </p>

  <p>
    <%= form.submit %>
  </p>


<% end %>

app/views/articles/edit.html.erb
<div class="formularz">
  <h1>Edit article</h1>
  <%= form_for @article,url: blog_article_path(@article.blog_id,@article), html: {multipart: true} do |form| %>

    <% if @article.errors.any? %>
      <div class="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.label :image %><br>
      <%= form.file_field :image %>
    </p>

    <p>
      <%= form.label :tags %><br>
      <%= form.text_field :tag_list, value: form.object.tag_list.to_s %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>

  <%= link_to 'Back', blog_path(@article.blog_id) %>
</div>

app/views/articles/index.html.erb
  <h1>All Articles from All Blogs</h1>
  <p class="pdf">
    <%= link_to "PDF", articles_path(format: 'pdf') %>
  </p>
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
    <% @article.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%=image_tag article.image(:thumb) %></td>
        <td><%= render article.tags %></td>

        <td><%= link_to 'Show', blog_article_path(article.blog_id,article) %></td>
      </tr>
    <% end %>
  </table>

app/views/articles/new.html.erb
<div class="formularz">
  <h1>New Article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', :back %>

</div>

app/views/articles/show.html.erb
<div class="formularz">
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>
  <p>
  <%=image_tag @article.image(:original) %>
  </p>
  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p><h4>Tags:</h4>
  <p><%= render @article.tags %></p>
  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
  <%= link_to 'Back', blog_path(@article.blog_id) %>
</div>