config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/show'

  get 'comments/destroy'

  get 'articles/index'

  root 'public_controller#home'
  get '/contact', to: 'public_controller#contact'
  get    '/all',  to: 'users#all'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/edit',  to: 'users#edit'
  get '/delete',  to: 'users#destroy'
  resources :users
  resources :blogs do
    resources :articles
  end
  resources :articles do
    resources :comments
  end
  resources :tags, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :blogs, dependent: :destroy
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password , presence: true, length: { minimum: 6 }, allow_nil: true
  validates_confirmation_of :password
  validates_presence_of :password_confirmation

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :all]
  def index
    render 'show'
    end
  def all
    @user = User.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = Users_pdf.new(@user)
        send_data pdf.render, filename: 'user.pdf', type: 'application/pdf', disposition: "inline"
      end
    end
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome !"
      log_in @user
      redirect_to blogs_path
      #redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  # Potwierdzenie zalogowanego użytkownika.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(size: 80)
    gravatar_id = Digest::MD5::hexdigest(current_user.email.downcase)
    gravatar_url = "https://s.gravatar.com/avatar/6764dfd61b4e991d6ca0a6fbe88d9a07?s=#{size}"
    image_tag(gravatar_url, alt: current_user.name, class: "gravatar")
  end
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render 'error_messages' %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <p>You have an account? <%= link_to "Sign up now!", login_path %></p>
<% end %>

app/views/users/all.html.erb
<h1>All Useer</h1>
<p class="pdf">
  <%= link_to "PDF", all_path(format: 'pdf') %>
</p>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
  </tr>
  <% @user.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<div class="formularz">
  <h1>Edit User Data</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', blogs_path %>
</div>

app/views/users/new.html.erb
<div class="formularz">
  <h1>New User</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', blogs_path %>
</div>

app/views/users/show.html.erb
<div class="pokaz">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1 class="pokaz">
          <%= gravatar_for %>
          <%= current_user.name %><br>
          <%= current_user.email %><br>
        </h1>
      </section>
    </aside>
  </div>
  <%= link_to 'Back', root_path %>
</div>