config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/show'

  get 'comments/destroy'

  get 'articles/index'

  root 'public_controller#home'
  get '/contact', to: 'public_controller#contact'
  get    '/all',  to: 'users#all'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/edit',  to: 'users#edit'
  get '/delete',  to: 'users#destroy'
  resources :users
  resources :blogs do
    resources :articles
  end
  resources :articles do
    resources :comments
  end
  resources :tags, only: [:index, :show]
end

app/views/layouts/_footer.html.erb
//Jeśli nie potrzebne będzie to usunąć
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="log">
  <ul>
  <% if logged_in? %>
    <li class="log"><%= link_to 'Logout', logout_path, method: :delete %></li>
  <% else %>
    <li id="log"><%= link_to 'Login ', login_path %></li>
    <li id="log"><%= link_to 'Register ', new_user_path %></li>
  <% end %>
  </ul>
</div>
<div class="menu">
  <ul>
    <li><%= link_to 'START', root_path %></li>
    <li><%= link_to 'BLOGS', blogs_path %></li>
    <li>DATA
      <% if current_user %>
        <ul>
          <li><%= link_to 'SHOW', users_path %></li>
          <li><%= link_to 'EDIT', edit_path %></li>
          <li><%= link_to 'DELETE', delete_path %></li>
        </ul>
      <% end %>
    </li>
    <li><%= link_to 'CONTACT', contact_path %></li>
  </ul>
</div>

app/views/layouts/_logo.html.erb
<h1 class="logo">
  <div id="rodzic">
    <span>B</span>
    <span>L</span>
    <span>O</span>
    <span>G</span>
    <span>G</span>
    <span>E</span>
    <span>R</span>
  </div>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projekt</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="pierwsza">
      <div class="main">
        <%= render 'layouts/logo' %>
        <%= render 'layouts/header' %>
      </div>
      <div class="druga trzecia">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>